### ISSUE TITLE
Sharing your models

### ISSUE THREAD

**Issue by amaumene** [lars-frogner/babymonitor#1]
Hi,

Are you going to share your models? Currently I'm facing this issue:
```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/babymonitor/control/listen.py", line 291, in process_features
    model = create_model(model_file)
  File "/home/pi/babymonitor/control/listen.py", line 320, in create_model
    model = Model(model_file)
  File "/home/pi/babymonitor/control/listen.py", line 22, in __init__
    self.model = cv2.dnn.readNetFromONNX(str(model_path))
cv2.error: OpenCV(4.5.3) /tmp/pip-wheel-p89zgche/opencv-python-headless_b4d2e1ad7f7640f78782ab7ec688685e/opencv/modules/dnn/src/onnx/onnx_importer.cpp:78: error: (-5:Bad argument) Can't read ONNX file: /home/pi/babymonitor/control/crynet_large.onnx in function 'ONNXImporter'

Traceback (most recent call last):
  File "/home/pi/babymonitor/control/listen.py", line 375, in <module>
    listen()
  File "/home/pi/babymonitor/control/listen.py", line 181, in listen
    control.enter_mode(
  File "/home/pi/babymonitor/control/control.py", line 61, in enter_mode
    six.reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/home/pi/babymonitor/control/control.py", line 56, in enter_mode
    run_mode(mode, config, database)
  File "/home/pi/babymonitor/control/listen.py", line 182, in <lambda>
    MODE, lambda mode, config, database: listen_with_settings(
  File "/home/pi/babymonitor/control/listen.py", line 190, in listen_with_settings
    listen_with_settings_network(*args, model=model, **kwargs)
  File "/home/pi/babymonitor/control/listen.py", line 269, in listen_with_settings_network
    feature_provider = create_feature_provider(config, control_dir,
  File "/home/pi/babymonitor/control/listen.py", line 348, in create_feature_provider
    return features.FeatureProvider(get_audio_device(),
  File "/home/pi/babymonitor/detection/features.py", line 522, in __init__
    super().__init__(**kwargs)
  File "/home/pi/babymonitor/detection/features.py", line 503, in __init__
    self.read_standardization_file(standardization_file)
  File "/home/pi/babymonitor/detection/features.py", line 506, in read_standardization_file
    standardization = np.load(standardization_file)
  File "/home/pi/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/babymonitor/control/standardization.npz'
```

Thanks in advance.

**Comment by lars-frogner** [comment]
Certainly, I have added them to the repo now.
